###

POST http://localhost:3003/signup
Content-Type: application/json

{
	"name": "Michael Scott",
	"email": "michael@dundermifflin.com",
	"password": "theboss",
	"role": "ADMIN"
}

###

POST http://localhost:3003/login
Content-Type: application/json

{
	"email": "michael@dundermifflin.com",
	"password": "theboss"
}

###

GET http://localhost:3003/user/all
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM1YzhhZjI2LTNmZTQtNDBkNi05NTk4LWZlMzY4NjUyMTQ1OSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYxMjM4MjcxOCwiZXhwIjoxNjEyMzgyNzc4fQ.7HwPJqCSwCna45IvzuLZxGpEJ1G0JfIy-Qn66lgCbYE

###

DELETE http://localhost:3003/user/35c8af26-3fe4-40d6-9598-fe3686521459
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YzY4ZDU2LWNiNGMtNDI2OC05ZTkxLWEwYzFlMGYzZDViMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYxMjQwMzExMCwiZXhwIjoxNjEyNDAzMTcwfQ.-_MgCEskvuQgONADuBvvZjDSp5xIli9DXsXBbXr1hsM